$('.slider-ok').slick({ dots: false, arrows: false, infinite: true, speed: 500, slidesToShow: 4, swipeToSlide: true, waitForAnimate: true, autoplaySpeed: 2000, autoplay: true, responsive: [{ breakpoint: 1200, settings: { slidesToShow: 3, infinite: true, dots: true } }, { breakpoint: 1024, settings: { slidesToShow: 3, infinite: true, dots: true } }, { breakpoint: 768, settings: { slidesToShow: 2, } }, { breakpoint: 480, settings: { slidesToShow: 2, } }] }); $(".hhh").each(function (index) { let text = $(this).text(); $(this).text(text.length > 30 ? text.substring(0, 27) + '...' : text); }); $(document).ready(function () { $(".acc-button").click(function () { $(".category-filter").toggle(500); }); }); $('.ttt').click(function () { $(this).toggleClass("bg-width"); }); var selected_item = null; function large(self) {
    if (selected_item != null && selected_item != self) { selected_item.style.width = ""; selected_item.classList.remove('bg-width'); }
    if (self.style.width == '100%') { self.style.width = ""; } else { self.style.width = "100%"; }
    selected_item = self;
}
var startingX, startingY, movingX, movingY; function touchStart(evt) { startingX = evt.touches[0].clientX; startingY = evt.touches[0].clientY; }
function touchMove(evt) { movingX = evt.touches[0].clientX; movingY = evt.touches[0].clientY; }
function touchEnd() { if (startingY + 10 < movingY) { $(".offcanvas").removeClass("add1", 1000); $(".offcanvas").addClass("remove1", 1000); } else if (startingY - 10 > movingY) { $(".offcanvas").addClass("add1", 1000); $(".offcanvas").removeClass("remove1", 1000); $(".offcanvas").removeClass("show", 1000); } }
if (document.getElementById("checkout-submit") != null) { document.getElementById("checkout-submit").disabled = true; document.getElementById("checkout-submit").style.opacity = 0.5; }
$("#checkout-submit").on('click', function () { $('#qr-gif').show(0); $('#qr-done').hide(0); $('#qr-main').hide(0); $('#qr-cancel').hide(0); }); $(document).ready(function () { $('.minus').click(function () { var $input = $(this).parent().find('input'); var count = parseInt($input.val()) - 1; count = count < 1 ? 1 : count; $input.val(count); $input.change(); return false; }); $('.plus').click(function () { var $input = $(this).parent().find('input'); $input.val(parseInt($input.val()) + 1); $input.change(); return false; }); }); const cartButtons = document.querySelectorAll('.cart-button'); document.addEventListener("DOMContentLoaded", function (event) { const cartButtons = document.querySelectorAll('.cart-button'); cartButtons.forEach(button => { button.addEventListener('click', cartClick); }); function cartClick() { let button = this; button.classList.add('clicked'); setTimeout(() => { $(this).removeClass('clicked'); }, 2000); } }); $(document).scroll(function () { var y = $(this).scrollTop(); if (y > 80) { $('.scroll-top').fadeIn(); } else { $('.scroll-top').fadeOut(); } });
